changes made to node helm chart and related ansible tasks
Signed-off-by: kaverikhaneja <kaveri.khaneja@accenture.com>

diff --git a/platforms/substrate/charts/substrate-node/templates/statefulset.yaml b/platforms/substrate/charts/substrate-node/templates/statefulset.yaml
--- a/platforms/substrate/charts/substrate-node/templates/statefulset.yaml
+++ b/platforms/substrate/charts/substrate-node/templates/statefulset.yaml
@@ -27,6 +27,7 @@ spec:
       labels:
       {{- include "node.labels" . | nindent 8 }}
     spec:
+      serviceAccountName: {{ $serviceAccountName }}
       {{- with .Values.imagePullSecrets }}
       imagePullSecrets:
       {{- toYaml . | nindent 8 }}
@@ -168,27 +169,6 @@ spec:
               readOnly: true
             {{- end }}
         {{- end }}
-        {{- if or .Values.node.customChainspecUrl .Values.node.collator.relayChainCustomChainspecUrl }}
-        - name: download-chainspec
-          image: {{ .Values.initContainer.image.repository }}:{{ .Values.initContainer.image.tag }}
-          command: [ "/bin/sh" ]
-          args:
-            - -c
-            - |
-              {{- if .Values.node.customChainspecUrl }}
-              if [ ! -f {{ .Values.node.customChainspecPath }} ]; then
-                wget -O {{ .Values.node.customChainspecPath }} {{ .Values.node.customChainspecUrl }}
-              fi
-              {{- end }}
-              {{- if .Values.node.collator.relayChainCustomChainspecUrl }}
-              if [ ! -f {{ .Values.node.relayChainCustomChainspecPath }} ]; then
-                wget -O {{ .Values.node.relayChainCustomChainspecPath }} {{ .Values.node.collator.relayChainCustomChainspecUrl }}
-              fi
-              {{- end }}
-          volumeMounts:
-            - name: chain-data
-              mountPath: /data
-        {{- end }}
         - name: node-secrets
           image: {{ .Values.vault.image }}
           imagePullPolicy: IfNotPresent
@@ -207,8 +187,6 @@ spec:
           args:
           - |-
             #!/bin/sh
-              apk update && apk add jq curl
-              mkdir secrets
               
               validateVaultResponse () {
                 if echo ${2} | grep "errors"; then
@@ -264,6 +242,27 @@ spec:
           - name: keystore
             mountPath: /secrets
             readOnly: false
+        {{- if or .Values.node.customChainspecUrl .Values.node.collator.relayChainCustomChainspecUrl }}
+        - name: download-chainspec
+          image: {{ .Values.initContainer.image.repository }}:{{ .Values.initContainer.image.tag }}
+          command: [ "/bin/sh" ]
+          args:
+            - -c
+            - |
+              {{- if .Values.node.customChainspecUrl }}
+              if [ ! -f {{ .Values.node.customChainspecPath }} ]; then
+                wget -O {{ .Values.node.customChainspecPath }} {{ .Values.node.customChainspecUrl }}
+              fi
+              {{- end }}
+              {{- if .Values.node.collator.relayChainCustomChainspecUrl }}
+              if [ ! -f {{ .Values.node.relayChainCustomChainspecPath }} ]; then
+                wget -O {{ .Values.node.relayChainCustomChainspecPath }} {{ .Values.node.collator.relayChainCustomChainspecUrl }}
+              fi
+              {{- end }}
+          volumeMounts:
+            - name: chain-data
+              mountPath: /data
+        {{- else }}
         - name: retrieve-chain-spec
           image: {{ .Values.vault.image }}
           imagePullPolicy: IfNotPresent
@@ -276,15 +275,11 @@ spec:
             value: {{ .Values.vault.authPath }}
           - name: VAULT_APP_ROLE
             value: {{ .Values.vault.appRole }}
-          - name: PEER_NAME
-            value: {{ .Values.node.name }}
           command: ["/bin/sh", "-c"]
           args:
           - |-
             #!/bin/sh
-              apk update && apk add jq curl
-              mkdir secrets
-              
+         
               validateVaultResponse () {
                 if echo ${2} | grep "errors"; then
                   echo "ERROR: unable to retrieve ${1}: ${2}"
@@ -317,9 +312,9 @@ spec:
               validateVaultResponse 'vault login token' "${VAULT_CLIENT_TOKEN}"
               echo "logged in"
 
-              vault_secret_key="${VAULT_SECRET_PREFIX}/${PEER_NAME}/chainSpec"
+              vault_secret_key="${VAULT_SECRET_PREFIX}/genesis"
               
-              echo "Getting chain spec from $vault_secret_key"
+              echo "Getting the chain spec from $vault_secret_key"
 
               LOOKUP_SECRET_RESPONSE=$(curl -sS \
                 --header "X-Vault-Token:${VAULT_CLIENT_TOKEN}" \
@@ -327,28 +322,45 @@ spec:
                 jq -r 'if .errors then . else . end')
               validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE" 
               
-              chain_spec=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["chain_spec"]')
-              echo "${chain_spec}" > /secrets/chain_spec.json
+              chain_spec=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["genesis"]')
+              echo "${chain_spec}" | base64 -d > /secrets/chain_spec.json
+              
+              echo "Retrieved the chain spec from vault."
           volumeMounts:
           - name: keystore
             mountPath: /secrets
             readOnly: false
-        {{- if .Values.node.keys }}
+        {{- end }}
         - name: inject-keys
           image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
           imagePullPolicy: {{ .Values.image.pullPolicy }}
           command: ["/bin/sh", "-c"]
           args:
           - |-
-            {{- range $keys := .Values.node.keys }}
-              {{ $.Values.node.command }} key insert --base-path /data \
-              --chain ${CHAIN} \
-              --key-type $(cat /var/run/secrets/{{ .type }}/type) \
-              --scheme $(cat /var/run/secrets/{{ .type }}/scheme) \
-              --suri /var/run/secrets/{{ .type }}/seed \
-              && echo "Inserted key {{ .type }} into Keystore" \
-              || echo "Failed to insert key {{ .type}} into Keystore."
-              {{- end }}
+            #!/bin/sh
+            {{- if .Values.node.keys }}
+              {{- range $keys := .Values.node.keys }}
+                {{ $.Values.node.command }} key insert --base-path /data \
+                --chain ${CHAIN} \
+                --key-type $(cat /var/run/secrets/{{ .type }}/type) \
+                --scheme $(cat /var/run/secrets/{{ .type }}/scheme) \
+                --suri /var/run/secrets/{{ .type }}/seed \
+                && echo "Inserted key {{ .type }} into Keystore" \
+                || echo "Failed to insert key {{ .type}} into Keystore."
+                {{- end }}
+            {{- else }}
+              exec {{ .Values.node.command }} key insert --base-path /data \
+              --chain /secrets/chain_spec.json \
+              --scheme Sr25519 \
+              --suri /secrets/aura_seed \
+              --key-type aura
+
+              exec {{ .Values.node.command }} key insert --base-path /data \
+              --chain /secrets/chain_spec.json \
+              --scheme Ed25519 \
+              --suri /secrets/grandpa_seed \
+              --key-type gran
+            {{- end }}
           env:
             - name: CHAIN
               value: {{ .Values.node.chain }}
@@ -361,7 +373,6 @@ spec:
             - mountPath: /var/run/secrets/{{ .type }}
               name: {{ .type }}
           {{- end }}
-        {{- end }}
         {{- if .Values.node.perNodeServices.createP2pNodePortService }}
         - name: retrieve-node-port
           image: {{ .Values.kubectl.image.repository }}:{{ .Values.kubectl.image.tag }}
@@ -388,7 +399,7 @@ spec:
             name: chain-data
         {{- end }}
       containers:
-        - name: {{ .Values.node.chain }}
+        - name: {{ .Values.node.name }}
           image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
           imagePullPolicy: {{ .Values.image.pullPolicy }}
           command: ["/bin/sh", "-c"]
@@ -417,11 +428,11 @@ spec:
                 {{- if eq .Values.node.role "collator" }}
                 --collator \
                 {{- end }}
-                {{- if eq .Values.node.role "light" }}
+                {{- if or (eq .Values.node.role "light") (eq .Values.node.role "member")  }}
                 --light \
                 {{- end }}
                 {{- if or (eq .Values.node.role "validator") (eq .Values.node.role "member") }}
-                --bootnodes {{ .Values.bootnode }}\
+                --bootnodes ${BOOTNODE} \
                 {{- end }}
                 {{- if .Values.node.collator.isParachain }}
                 {{- if .Values.node.perNodeServices.createP2pNodePortService }}
@@ -434,7 +445,7 @@ spec:
                 {{- end }}
                 {{- if .Values.node.persistGeneratedNodeKey }}
                 --node-key-file /data/node-key \
-                {{- else if .Values.node.customNodeKey }}
+                {{- else }}
                 --node-key $(cat /secrets/node_key) \
                 {{- end }}
                 {{- if .Values.node.tracing.enabled }}
@@ -457,6 +468,8 @@ spec:
                 --listen-addr=/ip4/0.0.0.0/tcp/30333 \
                 {{- join " " .Values.node.collator.relayChainFlags | nindent 16 }}
           env:
+            - name: BOOTNODE
+              value: {{ .Values.bootnode }}
             - name: CHAIN
               value: {{ .Values.node.chain }}
             - name: NODE_NAME
@@ -479,7 +492,6 @@ spec:
             - name: prometheus
               containerPort: 9615
               protocol: TCP
-        
           {{- if .Values.node.enableStartupProbe }}
           # On startup, retry the connection to the /health endpoint every 10s for 5 min before killing the container
           startupProbe:
