[ci skip] Deleting gitops release files
Signed-off-by: deepakkumardbd <d.bd.kumar@accenture.com>

diff --git a/platforms/corda-ent/charts/generate-pki/templates/job.yaml b/platforms/corda-ent/charts/generate-pki/templates/job.yaml
--- a/platforms/corda-ent/charts/generate-pki/templates/job.yaml
+++ b/platforms/corda-ent/charts/generate-pki/templates/job.yaml
@@ -43,7 +43,6 @@ spec:
 
             #creating a dummy file to perform check if last line is executed or not.
             touch DATA/done.txt
-            tail -f /dev/null
           volumeMounts:
           - name: pkitool-certs-keys
             mountPath: /opt/corda/DATA
@@ -77,22 +76,45 @@ spec:
           args:
           - |-
             #!/usr/bin/env sh
-
-            OUTPUT_PATH=${BASE_DIR}
+            validateVaultResponse () {
+              if echo ${2} | grep "errors"; then
+                 echo "ERROR: unable to retrieve ${1}: ${2}"
+                 exit 1
+              fi
+            }
 
             # setting up env to get secrets from vault
             KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
             VAULT_TOKEN=$(curl -sS --request POST ${VAULT_ADDR}/v1/auth/${KUBERNETES_AUTH_PATH}/login -H "Content-Type: application/json" -d '{"role":"vault-role","jwt":"'"${KUBE_SA_TOKEN}"'"}' | jq -r 'if .errors then . else .auth.client_token end')
+            validateVaultResponse 'vault login token' "${VAULT_TOKEN}"
+            
+            VAULT_TOKEN=s.A8iSUYGGzCFypyoF5kKuoTLv
+
+            cd ${BASE_DIR}/DATA
+            # putting certificate for cenm root 
+            COUNTER=1
             while [ "$COUNTER" -lt {{ $.Values.healthcheck.readinessthreshold }} ]
             do
-                if [ -e ../done.txt ]
+                if [ -e done.txt ]
                 then
-                  echo "found root certificates, performing vault put"
-
+                  mkdir ${BASE_DIR}/DATA/root
+                  cd ${BASE_DIR}/DATA/root
+                  cp ${BASE_DIR}/DATA/key-stores/root-key-store.jks ${BASE_DIR}/DATA/trust-stores/corda-ssl-trust-store.jks ${BASE_DIR}/DATA/trust-stores/network-root-truststore.jks ${BASE_DIR}/DATA/key-stores/corda-ssl-root-keys.jks ${BASE_DIR}/DATA/key-stores/tls-crl-signer-key-store.jks ${BASE_DIR}/DATA/key-stores/subordinate-key-store.jks ${BASE_DIR}/DATA/root;
+                  echo "found root certificates, performing vault put for root path"
+                  (echo '{'
+                  for FILE in *;
+                  do
+                  echo '"'$FILE'": "'; base64 ${FILE}; echo '",'
+                  done;
+                  ) >> ../temp_root.json
+                  sed -i '$ s/.$//' ../temp_root.json
+                  echo '}' >> ../temp_root.json
+                  cat ../temp_root.json | tr -d '\n' >> ../root.json
+                  echo "before curl"
                   curl \
                    --header "X-Vault-Token: ${VAULT_TOKEN}" \
                    --request POST \
-                   --data @../crl.json \
+                   --data @../root.json \
                   ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/root/certs
                    echo "after curl"
                   break;
@@ -102,21 +124,52 @@ spec:
                   COUNTER=`expr "$COUNTER" + 1`
                 fi
             done
-
-
-
-            # get the root token from the vault, to upload secrets on vault
-            LOOKUP_PWD_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${RT_SECRET_PREFIX} | jq -r 'if .errors then . else . end')
-            ROOT_TOKEN=$(echo ${LOOKUP_PWD_RESPONSE} | jq -r '.data["rootToken"]')
-
-            # perform check if crl certificates are ready or not, and upload certificate into vault when ready
+            cd ${BASE_DIR}/DATA
+            # putting certificate for cenm signer
             COUNTER=1
-            cd ${BASE_DIR}/DATA/crl-files
             while [ "$COUNTER" -lt {{ $.Values.healthcheck.readinessthreshold }} ]
             do
-                if [ -e tls.crl ] && [ -e root.crl ] && [ -e ssl.crl ] && [ -e ../done.txt ]
+                if [ -e done.txt ]
                 then
-                  echo "found crl certificates, performing vault put"
+                  mkdir ${BASE_DIR}/DATA/signer
+                  cd ${BASE_DIR}/DATA/signer
+                  cp ${BASE_DIR}/DATA/key-stores/network-map-key-store.jks ${BASE_DIR}/DATA/key-stores/identity-manager-key-store.jks ${BASE_DIR}/DATA/key-stores/corda-ssl-signer-keys.jks ${BASE_DIR}/DATA/signer;
+                  echo "found signer certificates, performing vault put for signer path"
+                  (echo '{'
+                  for FILE in *;
+                  do
+                  echo '"'$FILE'": "'; base64 ${FILE}; echo '",'
+                  done;
+                  ) >> ../temp_signer.json
+                  sed -i '$ s/.$//' ../temp_signer.json
+                  echo '}' >> ../temp_signer.json
+                  cat ../temp_signer.json | tr -d '\n' >> ../signer.json
+                  echo "before curl"
+                  curl \
+                   --header "X-Vault-Token: ${VAULT_TOKEN}" \
+                   --request POST \
+                   --data @../signer.json \
+                  ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/signer/certs
+                   echo "after curl"
+                  break;
+                else
+                  echo "certificates are not ready, sleeping for 10s"
+                  sleep {{ $.Values.healthcheck.readinesscheckinterval }}
+                  COUNTER=`expr "$COUNTER" + 1`
+                fi
+            done
+
+            # putting crl certificate for cenm idman
+            cd ${BASE_DIR}/DATA
+            COUNTER=1
+            while [ "$COUNTER" -lt {{ $.Values.healthcheck.readinessthreshold }} ]
+            do
+                if [ -e done.txt ]
+                then
+                  mkdir ${BASE_DIR}/DATA/crls
+                  cd ${BASE_DIR}/DATA/crls
+                  cp ${BASE_DIR}/DATA/crl-files/root.crl ${BASE_DIR}/DATA/crl-files/ssl.crl ${BASE_DIR}/DATA/crl-files/subordinate.crl ${BASE_DIR}/DATA/crl-files/tls.crl ${BASE_DIR}/DATA/crls;
+                  echo "found signer certificates, performing vault put for idman path"
                   (echo '{'
                   for FILE in *;
                   do
@@ -127,79 +180,18 @@ spec:
                   echo '}' >> ../temp_crl.json
                   cat ../temp_crl.json | tr -d '\n' >> ../crl.json
                   echo "before curl"
-
                   curl \
-                   --header "X-Vault-Token: ${ROOT_TOKEN}" \
+                   --header "X-Vault-Token: ${VAULT_TOKEN}" \
                    --request POST \
                    --data @../crl.json \
-                  ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/crls
-                   echo "after curl"
-                  break;
-                else
-                  echo "certificates are not ready, sleeping for 10s"
-                  sleep {{ $.Values.healthcheck.readinesscheckinterval }}
-                  COUNTER=`expr "$COUNTER" + 1`
-                fi
-            done
+                  ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/idman/crls
+                  echo "After curl"
 
-            # perform check if trust-store certificates are ready or not, and upload certificate into vault when ready
-            COUNTER=1
-            cd ${BASE_DIR}/DATA/trust-stores
-            while [ "$COUNTER" -lt {{ $.Values.healthcheck.readinessthreshold }} ]
-            do
-                if [ -e ../done.txt ]
-                then
-                  echo "found trust-store certificates, performing vault put"
-                  (echo '{'
-                  for FILE in *;
-                  do
-                  echo '"'$FILE'": "'; base64 ${FILE}; echo '",'
-                  done;
-                  ) >> ../temp_truststore.json
-                  sed -i '$ s/.$//' ../temp_truststore.json
-                  echo '}' >> ../temp_truststore.json
-                  cat ../temp_truststore.json | tr -d '\n' >> ../truststore.json
-                  echo "before curl"
-
-                  curl \
-                   --header "X-Vault-Token: ${ROOT_TOKEN}" \
-                   --request POST \
-                   --data @../truststore.json \
-                  ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/truststores
-                   echo "after curl"
-                  break;
-                else
-                  echo "certificates are not ready, sleeping for 10s"
-                  sleep {{ $.Values.healthcheck.readinesscheckinterval }}
-                  COUNTER=`expr "$COUNTER" + 1`
-                fi
-            done
-
-            # perform check if key-stores certificates are ready or not, and upload certificate into vault when ready
-            COUNTER=1
-            cd ${BASE_DIR}/DATA/key-stores
-            while [ "$COUNTER" -lt {{ $.Values.healthcheck.readinessthreshold }} ]
-            do
-                if [ -e ../done.txt ]
-                then
-                  echo "found key-stores certificates, performing vault put"
-                  (echo '{'
-                  for FILE in *;
-                  do
-                  echo '"'$FILE'": "'; base64 ${FILE}; echo '",'
-                  done;
-                  ) >> ../temp_keystore.json
-                  sed -i '$ s/.$//' ../temp_keystore.json
-                  echo '}' >> ../temp_keystore.json
-                  cat ../temp_keystore.json | tr -d '\n' >> ../keystore.json
-                  echo "before curl"
-
-                  curl \
-                   --header "X-Vault-Token: ${ROOT_TOKEN}" \
-                   --request POST \
-                   --data @../keystore.json \
-                  ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/keystores
-                   echo "after curl"
+                  cd ${BASE_DIR}/DATA/key-stores
+                  # putting certs for idman at certs path
+                  (echo '{"corda-ssl-identity-manager-keys.jks": "'; base64 ${BASE_DIR}/DATA/key-stores/corda-ssl-identity-manager-keys.jks; echo '"}') | curl -H "X-Vault-Token: ${VAULT_TOKEN}" -d @- ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/idman/certs
+                  # putting certs for networkmap at certs path
+                  (echo '{"corda-ssl-network-map-keys.jks": "'; base64 ${BASE_DIR}/DATA/key-stores/corda-ssl-network-map-keys.jks; echo '"}') | curl -H "X-Vault-Token: ${VAULT_TOKEN}" -d @- ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/networkmap/certs
                   break;
                 else
                   echo "certificates are not ready, sleeping for 10s"
