Merge from develop (#936)
* [ci skip] Develop merge

Signed-off-by: sownak <sownak.roy@accenture.com>

diff --git a/platforms/corda-ent/charts/generate-pki/templates/job.yaml b/platforms/corda-ent/charts/generate-pki/templates/job.yaml
--- a/platforms/corda-ent/charts/generate-pki/templates/job.yaml
+++ b/platforms/corda-ent/charts/generate-pki/templates/job.yaml
@@ -1,11 +1,11 @@
 apiVersion: batch/v1
 kind: Job
 metadata:
-  name: {{ .Values.nodeName }}-setup
+  name: {{ .Values.nodeName }}-generate-pki
   namespace: {{ .Values.metadata.namespace }}
   labels:
-    app: {{ .Values.nodeName }}-setup
-    app.kubernetes.io/name: {{ .Values.nodeName }}-setup
+    app: {{ .Values.nodeName }}-generate-pki
+    app.kubernetes.io/name: {{ .Values.nodeName }}-generate-pki
     helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
     app.kubernetes.io/managed-by: {{ .Release.Service }}
     app.kubernetes.io/instance: {{ .Release.Name }}
@@ -15,8 +15,8 @@ spec:
     template:
       metadata:
         labels:
-          app: {{ .Values.nodeName }}-setup
-          app.kubernetes.io/name: {{ .Values.nodeName }}-setup
+          app: {{ .Values.nodeName }}-generate-pki
+          app.kubernetes.io/name: {{ .Values.nodeName }}-generate-pki
           app.kubernetes.io/instance: {{ .Release.Name }}
       spec:
         restartPolicy: "OnFailure"
@@ -34,11 +34,11 @@ spec:
           command: ["/bin/bash", "-c"]
           args:
           - |-
-            rm -rF DATA/done.txt
+            rm -r DATA/done.txt
 
             cp CM-FILES/pki.conf etc/pki.conf
             cp CM-FILES/signer.conf etc/signer.conf;
-            mkdir DATA/key-stores DATA/trust-stores DATA/crl-files
+            mkdir DATA/signer DATA/root DATA/networkmap DATA/idman DATA/idman/crls DATA/idman/certs
             time java -Xmx{{ .Values.cordaJarMx }}G -jar {{ .Values.jarPath }}/pkitool.jar --config-file {{ .Values.configPath }}/pki.conf
 
             #creating a dummy file to perform check if last line is executed or not.
@@ -68,8 +68,6 @@ spec:
                value: {{ $.Values.vault.role }}
              - name: BASE_DIR
                value: {{ $.Values.volume.baseDir }}
-             - name: RT_SECRET_PREFIX
-               value: {{ .Values.vault.tokensecretprefix }}
              - name: CERTS_SECRET_PREFIX
                value: {{ .Values.vault.certsecretprefix }}
              - name: JAVA_OPTIONS
@@ -78,25 +76,91 @@ spec:
           args:
           - |-
             #!/usr/bin/env sh
-
-            OUTPUT_PATH=${BASE_DIR}
+            validateVaultResponse () {
+              if echo ${2} | grep "errors"; then
+                 echo "ERROR: unable to retrieve ${1}: ${2}"
+                 exit 1
+              fi
+            }
 
             # setting up env to get secrets from vault
             KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
             VAULT_TOKEN=$(curl -sS --request POST ${VAULT_ADDR}/v1/auth/${KUBERNETES_AUTH_PATH}/login -H "Content-Type: application/json" -d '{"role":"vault-role","jwt":"'"${KUBE_SA_TOKEN}"'"}' | jq -r 'if .errors then . else .auth.client_token end')
-
-            # get the root token from the vault, to upload secrets on vault
-            LOOKUP_PWD_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${RT_SECRET_PREFIX} | jq -r 'if .errors then . else . end')
-            ROOT_TOKEN=$(echo ${LOOKUP_PWD_RESPONSE} | jq -r '.data["rootToken"]')
-
-            # perform check if crl certificates are ready or not, and upload certificate into vault when ready
+            validateVaultResponse 'vault login token' "${VAULT_TOKEN}"
+            cd ${BASE_DIR}/DATA
+            # putting certificate for cenm root 
             COUNTER=1
-            cd ${BASE_DIR}/DATA/crl-files
             while [ "$COUNTER" -lt {{ $.Values.healthcheck.readinessthreshold }} ]
             do
-                if [ -e tls.crl ] && [ -e root.crl ] && [ -e ssl.crl ] && [ -e ../done.txt ]
+                if [ -e done.txt ]
                 then
-                  echo "found crl certificates, performing vault put"
+                  cd ${BASE_DIR}/DATA/root
+                  echo "found root certificates, performing vault put for root path"
+                  (echo '{'
+                  for FILE in *;
+                  do
+                  echo '"'$FILE'": "'; base64 ${FILE}; echo '",'
+                  done;
+                  ) >> ../temp_root.json
+                  sed -i '$ s/.$//' ../temp_root.json
+                  echo '}' >> ../temp_root.json
+                  cat ../temp_root.json | tr -d '\n' >> ../root.json
+                  echo "before curl"
+                  curl \
+                   --header "X-Vault-Token: ${VAULT_TOKEN}" \
+                   --request POST \
+                   --data @../root.json \
+                  ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/root/certs
+                   echo "after curl"
+                  break;
+                else
+                  echo "certificates are not ready, sleeping for 10s"
+                  sleep {{ $.Values.healthcheck.readinesscheckinterval }}
+                  COUNTER=`expr "$COUNTER" + 1`
+                fi
+            done
+            cd ${BASE_DIR}/DATA
+            # putting certificate for cenm signer
+            COUNTER=1
+            while [ "$COUNTER" -lt {{ $.Values.healthcheck.readinessthreshold }} ]
+            do
+                if [ -e done.txt ]
+                then
+                  cd ${BASE_DIR}/DATA/signer
+                  echo "found signer certificates, performing vault put for signer path"
+                  (echo '{'
+                  for FILE in *;
+                  do
+                  echo '"'$FILE'": "'; base64 ${FILE}; echo '",'
+                  done;
+                  ) >> ../temp_signer.json
+                  sed -i '$ s/.$//' ../temp_signer.json
+                  echo '}' >> ../temp_signer.json
+                  cat ../temp_signer.json | tr -d '\n' >> ../signer.json
+                  echo "before curl"
+                  curl \
+                   --header "X-Vault-Token: ${VAULT_TOKEN}" \
+                   --request POST \
+                   --data @../signer.json \
+                  ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/{{ $.Values.cenmServices.signerName }}/certs
+                   echo "after curl"
+                  break;
+                else
+                  echo "certificates are not ready, sleeping for 10s"
+                  sleep {{ $.Values.healthcheck.readinesscheckinterval }}
+                  COUNTER=`expr "$COUNTER" + 1`
+                fi
+            done
+
+            # putting idman certificate for cenm idman
+            cd ${BASE_DIR}/DATA
+            COUNTER=1
+            while [ "$COUNTER" -lt {{ $.Values.healthcheck.readinessthreshold }} ]
+            do
+                if [ -e done.txt ]
+                then
+                  cd ${BASE_DIR}/DATA/idman/crls
+                  echo "found idman certificates, performing vault put for idman path"
                   (echo '{'
                   for FILE in *;
                   do
@@ -107,79 +171,17 @@ spec:
                   echo '}' >> ../temp_crl.json
                   cat ../temp_crl.json | tr -d '\n' >> ../crl.json
                   echo "before curl"
-
                   curl \
-                   --header "X-Vault-Token: ${ROOT_TOKEN}" \
+                   --header "X-Vault-Token: ${VAULT_TOKEN}" \
                    --request POST \
                    --data @../crl.json \
-                  ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/crls
-                   echo "after curl"
-                  break;
-                else
-                  echo "certificates are not ready, sleeping for 10s"
-                  sleep {{ $.Values.healthcheck.readinesscheckinterval }}
-                  COUNTER=`expr "$COUNTER" + 1`
-                fi
-            done
+                  ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/{{ $.Values.cenmServices.idmanName }}/crls
+                  echo "After curl"
 
-            # perform check if trust-store certificates are ready or not, and upload certificate into vault when ready
-            COUNTER=1
-            cd ${BASE_DIR}/DATA/trust-stores
-            while [ "$COUNTER" -lt {{ $.Values.healthcheck.readinessthreshold }} ]
-            do
-                if [ -e ../done.txt ]
-                then
-                  echo "found trust-store certificates, performing vault put"
-                  (echo '{'
-                  for FILE in *;
-                  do
-                  echo '"'$FILE'": "'; base64 ${FILE}; echo '",'
-                  done;
-                  ) >> ../temp_truststore.json
-                  sed -i '$ s/.$//' ../temp_truststore.json
-                  echo '}' >> ../temp_truststore.json
-                  cat ../temp_truststore.json | tr -d '\n' >> ../truststore.json
-                  echo "before curl"
-
-                  curl \
-                   --header "X-Vault-Token: ${ROOT_TOKEN}" \
-                   --request POST \
-                   --data @../truststore.json \
-                  ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/truststores
-                   echo "after curl"
-                  break;
-                else
-                  echo "certificates are not ready, sleeping for 10s"
-                  sleep {{ $.Values.healthcheck.readinesscheckinterval }}
-                  COUNTER=`expr "$COUNTER" + 1`
-                fi
-            done
-
-            # perform check if key-stores certificates are ready or not, and upload certificate into vault when ready
-            COUNTER=1
-            cd ${BASE_DIR}/DATA/key-stores
-            while [ "$COUNTER" -lt {{ $.Values.healthcheck.readinessthreshold }} ]
-            do
-                if [ -e ../done.txt ]
-                then
-                  echo "found key-stores certificates, performing vault put"
-                  (echo '{'
-                  for FILE in *;
-                  do
-                  echo '"'$FILE'": "'; base64 ${FILE}; echo '",'
-                  done;
-                  ) >> ../temp_keystore.json
-                  sed -i '$ s/.$//' ../temp_keystore.json
-                  echo '}' >> ../temp_keystore.json
-                  cat ../temp_keystore.json | tr -d '\n' >> ../keystore.json
-                  echo "before curl"
-
-                  curl \
-                   --header "X-Vault-Token: ${ROOT_TOKEN}" \
-                   --request POST \
-                   --data @../keystore.json \
-                  ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/keystores
-                   echo "after curl"
+                  # putting certs for idman at certs path
+                  (echo '{"corda-ssl-identity-manager-keys.jks": "'; base64 ${BASE_DIR}/DATA/idman/certs/corda-ssl-identity-manager-keys.jks; echo '"}') | curl -H "X-Vault-Token: ${VAULT_TOKEN}" -d @- ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/{{ $.Values.cenmServices.idmanName }}/certs
+                  # putting certs for networkmap at certs path
+                  (echo '{"corda-ssl-network-map-keys.jks": "'; base64 ${BASE_DIR}/DATA/networkmap/corda-ssl-network-map-keys.jks; echo '"}') | curl -H "X-Vault-Token: ${VAULT_TOKEN}" -d @- ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/{{ $.Values.cenmServices.networkmapName }}/certs
                   break;
                 else
                   echo "certificates are not ready, sleeping for 10s"
