Revert "Fabric 2.2v update"
This reverts commit 4753b68a9b9117f47952afab2fca86ccaa955d8c.
"revert"

diff --git a/platforms/corda-ent/charts/notary/templates/deployment.yaml b/platforms/corda-ent/charts/notary/templates/deployment.yaml
--- a/platforms/corda-ent/charts/notary/templates/deployment.yaml
+++ b/platforms/corda-ent/charts/notary/templates/deployment.yaml
@@ -4,9 +4,9 @@ kind: Deployment
 metadata:
   name: {{ .Values.nodeName }}
   namespace: {{ .Values.metadata.namespace }}
-  {{- if .Values.nodeConf.deployment.annotations }}
+  {{- if .Values.deployment.annotations }}
   annotations:
-{{ toYaml .Values.nodeConf.deployment.annotations | indent 8 }}
+{{ toYaml .Values.deployment.annotations | indent 8 }}
     {{- end }}
   labels:
     app.kubernetes.io/name: {{ .Values.nodeName }}
@@ -27,11 +27,11 @@ spec:
         app.kubernetes.io/name: {{ .Values.nodeName }}
         app.kubernetes.io/instance: {{ .Release.Name }}
     spec:
-      serviceAccountName: {{ $.Values.vault.serviceAccountName }}
+      serviceAccountName: {{ $.Values.vault.serviceaccountname }}
       securityContext:
         fsGroup: 1000
       initContainers:
-      - name: init-check-registration
+      - name: init-checkregistration
         image: {{ .Values.image.initContainerName }}
         imagePullPolicy: Always
         env:
@@ -40,9 +40,9 @@ spec:
           - name: VAULT_APP_ROLE
             value: {{.Values.vault.role}}
           - name: KUBERNETES_AUTH_PATH
-            value: {{ $.Values.vault.authPath }}
+            value: {{ $.Values.vault.authpath }}
           - name: CERTS_SECRET_PREFIX
-            value: {{ .Values.vault.certSecretPrefix }}
+            value: {{ .Values.vault.certsecretprefix }}
         command: ["sh", "-c"]
         args:
         - |-
@@ -61,20 +61,20 @@ spec:
             validateVaultResponse 'vault login token' "${VAULT_TOKEN}"
             echo "logged into vault"
             COUNTER=1
-            while [ "$COUNTER" -lt {{ $.Values.vault.retries }} ]
+            while [ "$COUNTER" -lt {{ $.Values.healthcheck.readinessthreshold }} ]
             do
                 # get truststore from vault to see if registration is done or not
                 LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/{{ $.Values.nodeName }}/certs/truststore | jq -r 'if .errors then . else . end')
                 if echo ${LOOKUP_SECRET_RESPONSE} | grep "errors"
                 then
-                  sleep {{ $.Values.vault.retryInterval }}
+                  sleep {{ $.Values.healthcheck.readinesscheckinterval }}
                 else
                   break
                 fi 
                 COUNTER=`expr "$COUNTER" + 1`
             done
 
-            if [ "$COUNTER" -ge {{ $.Values.vault.retries }} ]
+            if [ "$COUNTER" -ge {{ $.Values.healthcheck.readinessthreshold }} ]
             then
               # printing number of trial done before giving up
               echo "$COUNTER"
@@ -89,31 +89,48 @@ spec:
           - name: VAULT_ADDR
             value: {{ $.Values.vault.address }}
           - name: KUBERNETES_AUTH_PATH
-            value: {{ $.Values.vault.authPath }}
+            value: {{ $.Values.vault.authpath }}
           - name: VAULT_APP_ROLE
             value: {{ $.Values.vault.role }}
           - name: BASE_DIR
-            value: {{ $.Values.nodeConf.volume.baseDir }}
+            value: {{ $.Values.volume.baseDir }}
           - name: CERTS_SECRET_PREFIX
-            value: {{ .Values.vault.certSecretPrefix }}
+            value: {{ .Values.vault.certsecretprefix }}
+          - name: NODEINFO_MOUNT_PATH
+            value: "/notary-nodeinfo"                          
         command: ["sh", "-c"]
         args:
         - |-
               #!/usr/bin/env sh
               validateVaultResponse () {
-                if echo ${2} | grep "errors"; then
-                  echo "ERROR: unable to retrieve ${1}: ${2}"
-                  exit 1
-                fi
+              if echo ${2} | grep "errors"; then
+              echo "ERROR: unable to retrieve ${1}: ${2}"
+              exit 1
+              fi
               }
-
               # setting up env to get secrets from vault
               echo "Getting secrets from Vault Server"
               KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
               VAULT_TOKEN=$(curl -sS --request POST ${VAULT_ADDR}/v1/auth/${KUBERNETES_AUTH_PATH}/login -H "Content-Type: application/json" -d '{"role":"'"${VAULT_APP_ROLE}"'","jwt":"'"${KUBE_SA_TOKEN}"'"}' | jq -r 'if .errors then . else .auth.client_token end')
               validateVaultResponse 'vault login token' "${VAULT_TOKEN}"
-              OUTPUT_PATH=${BASE_DIR}/certificates              
-              # Getting intitial network parameters from Vault
+              OUTPUT_PATH=${BASE_DIR}/certificates
+
+              # Getting initial-node Info File from Vault
+              COUNTER=1
+              while [ "$COUNTER" -lt {{ $.Values.healthcheck.readinessthreshold }} ]
+              do 
+                LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/{{ $.Values.nodeName }}/nodeInfo | jq -r 'if .errors then . else . end')
+                if echo ${LOOKUP_SECRET_RESPONSE} | grep "errors"
+                  then
+                    sleep {{ $.Values.healthcheck.readinesscheckinterval }}
+                  else
+                    notary_nodeinfo=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["nodeInfoFile"]')
+                    echo "${notary_nodeinfo}" | base64 -d > ${NODEINFO_MOUNT_PATH}/notary_nodeinfo
+                    echo "Successfully got node info file"
+                    break
+                fi
+                COUNTER=`expr "$COUNTER" + 1`
+              done
 
               # get nodekeystore.jks from vault
               LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/{{ $.Values.nodeName }}/certs/nodekeystore | jq -r 'if .errors then . else . end')
@@ -141,11 +158,14 @@ spec:
               LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/{{ .Values.networkServices.networkmapName }}/tlscerts | jq -r 'if .errors then . else . end')
               validateVaultResponse "secret (${CERTS_SECRET_PREFIX}/{{ .Values.networkServices.networkmapName }}/tlscerts)" "${LOOKUP_SECRET_RESPONSE}"
               NETWORKMAP_CERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["tlscacerts"]')
-              echo "${NETWORKMAP_CERT}" | base64 -d > ${OUTPUT_PATH}/networkmap.crt             
-              echo "Done fetching all certificates from vault"
+              echo "${NETWORKMAP_CERT}" | base64 -d > ${OUTPUT_PATH}/networkmap.crt
+              
+              echo "Done"
         volumeMounts:
         - name: notary-certificates
-          mountPath: {{ $.Values.nodeConf.volume.baseDir }}/certificates
+          mountPath: {{ $.Values.volume.baseDir }}/certificates
+        - name: notary-nodeinfo
+          mountPath: /notary-nodeinfo
       - name: db-healthcheck
         image: {{ .Values.image.initContainerName }}
         imagePullPolicy: Always
@@ -187,13 +207,13 @@ spec:
           fi
       containers:
       - name: notary
-        image: "{{ .Values.image.nodeContainerName }}"
-        imagePullPolicy: {{ .Values.image.pullPolicy }}
+        image: "{{ required "notary[main]: missing value for .Values.dockerImage.name" .Values.dockerImage.name }}"
+        imagePullPolicy: {{ .Values.dockerImage.pullPolicy }}
         env:
           - name: ACCEPT_LICENSE
             value: "{{required "You must accept the license agreement to run this software" .Values.acceptLicense }}"
           - name: BASE_DIR
-            value: {{ $.Values.nodeConf.volume.baseDir }}
+            value: {{ $.Values.volume.baseDir }}
         command: ["/bin/bash", "-c"]
         args:
         - |-
@@ -209,35 +229,38 @@ spec:
           bin/run.sh
         volumeMounts:
         - name: notary-conf
-          mountPath: {{ $.Values.nodeConf.volume.baseDir }}/etc
+          mountPath: {{ $.Values.volume.baseDir }}/etc
           readOnly: false
         - name: notary-certificates
-          mountPath: {{ $.Values.nodeConf.volume.baseDir }}/certificates
+          mountPath: {{ $.Values.volume.baseDir }}/certificates
           readOnly: false
         - name: notary-volume
-          mountPath: {{ $.Values.nodeConf.volume.baseDir }}
+          mountPath: {{ $.Values.volume.baseDir }}
+          readOnly: false
+        - name: notary-nodeinfo
+          mountPath: {{ $.Values.volume.baseDir }}/additional-node-infos
           readOnly: false
         resources:
           requests:
-            memory: {{ .Values.nodeConf.pod.resources.requests }}
+            memory: {{ .Values.cordaJarMx }}M
           limits:
-            memory: {{ .Values.nodeConf.pod.resources.limits }}
+            memory: {{ add .Values.cordaJarMx 2 }}M
       - name: logs
-        image: "{{ .Values.image.nodeContainerName }}"
-        imagePullPolicy: {{ .Values.image.pullPolicy }}
+        image: "{{ required "notary[logs]: missing value for .Values.dockerImage.name" .Values.dockerImage.name }}"
+        imagePullPolicy: {{ .Values.dockerImage.pullPolicy }}
         env:
           - name: ACCEPT_LICENSE
             value: "{{required "You must accept the license agreement to run this software" .Values.acceptLicense }}"
         command: ["/bin/bash", "-c"]
         args:
         - |-
-          cd {{ $.Values.nodeConf.volume.baseDir }}/
+          cd {{ $.Values.volume.baseDir }}/
           while true; do tail -f logs/*.log 2>/dev/null; sleep 5; done
           # in case sth went wrong just wait indefinitely ...
           tail -f /dev/null
         volumeMounts:
         - name: notary-volume
-          mountPath: {{ $.Values.nodeConf.volume.baseDir }}
+          mountPath: {{ $.Values.volume.baseDir }}
       imagePullSecrets:
       - name: {{ .Values.image.imagePullSecret }}
       volumes:
@@ -250,3 +273,6 @@ spec:
       - name: notary-volume
         persistentVolumeClaim:
           claimName: {{ .Values.nodeName }}-volume
+      - name: notary-nodeinfo
+        emptyDir:
+          medium: Memory
