Enhancing vault responses for corda os
Signed-off-by: Kumar, D. bd <d.bd.kumar@accenture.com>

diff --git a/platforms/r3-corda/charts/doorman-tls/templates/deployment.yaml b/platforms/r3-corda/charts/doorman-tls/templates/deployment.yaml
--- a/platforms/r3-corda/charts/doorman-tls/templates/deployment.yaml
+++ b/platforms/r3-corda/charts/doorman-tls/templates/deployment.yaml
@@ -95,23 +95,36 @@ spec:
         args:
         - |-
              #!/usr/bin/env sh
-             validateVaultResponse () {
-             if echo ${2} | grep "errors"; then
-              echo "ERROR: unable to retrieve ${1}: ${2}"
-              exit 1
-              fi
-             }
+              validateVaultResponse () {
+                if echo ${2} | grep "errors"; then
+                  echo "ERROR: unable to retrieve ${1}: ${2}"
+                  exit 1
+                fi
+                if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
+                then
+                  http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
+                  --header "X-Vault-Token: ${VAULT_TOKEN}" \
+                  ${VAULT_ADDR}/v1/${1})
+                  curl_response=$?
+                  if test "$http_code" != "200" ; then
+                      echo "Http response code from Vault - $http_code"
+                      if test "$curl_response" != "0"; then
+                        echo "Error: curl command failed with error code - $curl_response"
+                        exit 1
+                      fi
+                  fi
+                fi
+              }
 
              KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
              echo "Getting secrets from Vault Server"
              VAULT_TOKEN=$(curl -sS --request POST ${VAULT_ADDR}/v1/auth/${KUBERNETES_AUTH_PATH}/login -H "Content-Type: application/json" -d '{"role":"'"${VAULT_APP_ROLE}"'","jwt":"'"${KUBE_SA_TOKEN}"'"}' | jq -r 'if .errors then . else .auth.client_token end')
              validateVaultResponse 'vault login token' "${VAULT_TOKEN}"
-             echo "logged into vault"
              OUTPUT_PATH=${MOUNT_PATH}
 
              LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/{{ .Values.vault.certsecretprefix }} | jq -r 'if .errors then . else . end')
 
-             validateVaultResponse "secret ({{ .Values.vault.certsecretprefix }})" "${LOOKUP_SECRET_RESPONSE}"
+             validateVaultResponse "{{ .Values.vault.certsecretprefix }}" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
 
              ROOTCA_KEY=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["rootcakey"]')
              mkdir -p ${OUTPUT_PATH}/root;
@@ -146,8 +159,22 @@ spec:
           #!/usr/bin/env sh
           validateVaultResponse () {
             if echo ${2} | grep "errors"; then
-               echo "ERROR: unable to retrieve ${1}: ${2}"
-               exit 1
+              echo "ERROR: unable to retrieve ${1}: ${2}"
+              exit 1
+            fi
+            if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
+            then
+              http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
+              --header "X-Vault-Token: ${VAULT_TOKEN}" \
+              ${VAULT_ADDR}/v1/${1})
+              curl_response=$?
+              if test "$http_code" != "200" ; then
+                  echo "Http response code from Vault - $http_code"
+                  if test "$curl_response" != "0"; then
+                    echo "Error: curl command failed with error code - $curl_response"
+                    exit 1
+                  fi
+              fi
             fi
           }
           
@@ -163,7 +190,7 @@ spec:
           then 
               # get doorman tls cert and key from vault          
               LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/{{ .Values.vault.tlscertsecretprefix }} | jq -r 'if .errors then . else . end')
-              validateVaultResponse "secret ({{ .Values.vault.tlscertsecretprefix }})" "${LOOKUP_SECRET_RESPONSE}"             
+              validateVaultResponse "{{ .Values.vault.tlscertsecretprefix }}" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
               DOORMAN_CRT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["tlscacerts"]')
               DOORMAN_KEY=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["tlskey"]')
               echo "${DOORMAN_CRT}" | base64 -d > {{ .Values.image.mountPath.basePath }}-tls/certs/doorman.crt 
@@ -172,7 +199,7 @@ spec:
 
           # get mongo tls cert from vault
           LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/{{ .Values.vault.dbcertsecretprefix }} | jq -r 'if .errors then . else . end')
-          validateVaultResponse "secret {{ .Values.vault.dbcertsecretprefix }}" "${LOOKUP_SECRET_RESPONSE}"
+          validateVaultResponse "{{ .Values.vault.dbcertsecretprefix }}" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
           CA_CERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["mongoCA.crt"]')
           echo "${CA_CERT}" | base64 -d > ${OUTPUT_PATH}/mongoCA.crt
           
@@ -204,12 +231,26 @@ spec:
         args:
         - |-
              #!/usr/bin/env sh
-             validateVaultResponse () {
-             if echo ${2} | grep "errors"; then
-              echo "ERROR: unable to retrieve ${1}: ${2}"
-              exit 1
-              fi
-             }
+              validateVaultResponse () {
+                if echo ${2} | grep "errors"; then
+                  echo "ERROR: unable to retrieve ${1}: ${2}"
+                  exit 1
+                fi
+                if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
+                then
+                  http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
+                  --header "X-Vault-Token: ${VAULT_TOKEN}" \
+                  ${VAULT_ADDR}/v1/${1})
+                  curl_response=$?
+                  if test "$http_code" != "200" ; then
+                      echo "Http response code from Vault - $http_code"
+                      if test "$curl_response" != "0"; then
+                        echo "Error: curl command failed with error code - $curl_response"
+                        exit 1
+                      fi
+                  fi
+                fi
+              }
 
              KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
              echo "Getting secrets from Vault Server"
@@ -219,11 +260,13 @@ spec:
              OUTPUT_PATH=${MOUNT_PATH}
              LOOKUP_PWD_RESPONSE_DB_PASS=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${DB_CRED_SECRET_PREFIX} | jq -r 'if .errors then . else . end')
              
+             validateVaultResponse "${DB_CRED_SECRET_PREFIX}" "${LOOKUP_PWD_RESPONSE_DB_PASS}" "LOOKUPSECRETRESPONSE"
+
              MONGODB_PASSWORD=$(echo ${LOOKUP_PWD_RESPONSE_DB_PASS} | jq -r '.data["mongodbPassword"]')
              echo "${MONGODB_PASSWORD}" >> ${MOUNT_PATH}/db_root_password
              cat ${MOUNT_PATH}/db_root_password
              LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${USER_SECRET_PREFIX} | jq -r 'if .errors then . else . end')
-             validateVaultResponse "secret (${CERTS_SECRET_PREFIX})" "${LOOKUP_SECRET_RESPONSE}"
+             validateVaultResponse "${USER_SECRET_PREFIX}" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
              
              USER_PASSWORD=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["{{ .Values.image.authusername }}"]')
              echo "${USER_PASSWORD}" >> ${MOUNT_PATH}/user_cred
diff --git a/platforms/r3-corda/charts/mongodb/templates/deployment.yaml b/platforms/r3-corda/charts/mongodb/templates/deployment.yaml
--- a/platforms/r3-corda/charts/mongodb/templates/deployment.yaml
+++ b/platforms/r3-corda/charts/mongodb/templates/deployment.yaml
@@ -61,10 +61,24 @@ spec:
         - |-
            #!/usr/bin/env sh
             validateVaultResponse () {
-            if echo ${2} | grep "errors"; then
-             echo "ERROR: unable to retrieve ${1}: ${2}"
-             exit 1
-             fi
+              if echo ${2} | grep "errors"; then
+                echo "ERROR: unable to retrieve ${1}: ${2}"
+                exit 1
+              fi
+              if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
+              then
+                http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
+                --header "X-Vault-Token: ${VAULT_TOKEN}" \
+                ${VAULT_ADDR}/v1/${1})
+                curl_response=$?
+                if test "$http_code" != "200" ; then
+                    echo "Http response code from Vault - $http_code"
+                    if test "$curl_response" != "0"; then
+                      echo "Error: curl command failed with error code - $curl_response"
+                      exit 1
+                    fi
+                fi
+              fi
             }
             echo "Getting secrets from Vault Server"
            
@@ -74,6 +88,9 @@ spec:
 
             OUTPUT_PATH=${MOUNT_PATH}
             LOOKUP_PWD_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${SECRET_PREFIX} | jq -r 'if .errors then . else . end')
+
+            validateVaultResponse "${SECRET_PREFIX}" "${LOOKUP_PWD_RESPONSE}" "LOOKUPSECRETRESPONSE"
+
             MONGODB_PASSWORD=$(echo ${LOOKUP_PWD_RESPONSE} | jq -r '.data["mongodbPassword"]')
             
             echo "${MONGODB_PASSWORD}" >> ${MOUNT_PATH}/db_root_password
