End release merge (#1363)
* Proxy none option for Corda OS (#1303)

Signed-off-by: suvajit-sarkar <suvajit.sarkar@accenture.com>

* Updated add-new-channel file and channel artifacts role

Signed-off-by: alvaropicazo <alvaro.picazo.haase@accenture.com>

* Use shared roles for chaincode checks

Signed-off-by: ragalz <r.galan.lopez@accenture.com>

* Fix for issue #1179

Signed-off-by: Kumar, D. bd <d.bd.kumar@accenture.com>

* Added update consortium genesis with sysychannel

Signed-off-by: alvaropicazo <alvaro.picazo.haase@accenture.com>

* [ fabric ] Vault fix

Signed-off-by: Roy,Sownak <sownak.roy@accenture.com>

* Updated affiliation to have fully saved certs for user1

Signed-off-by: alvaropicazo <alvaro.picazo.haase@accenture.com>

* Bug fix for different number of orgs in channel section than org section

Signed-off-by: Kumar, D. bd <d.bd.kumar@accenture.com>

* Tested and Fixed pre-existing molecule scenarios

Signed-off-by: TonyRowntree <33454202+TonyRowntree@users.noreply.github.com>

* Revert "[fabric] #1314 Fix and test existing molecule scenarios"

* Fixed addition of new anchor peer to the existing org

Signed-off-by: alvaropicazo <alvaro.picazo.haase@accenture.com>

* Fixed molecule scenario: Crypto, Default and pre-vault-setup. Created new molecule scenario orderer

Signed-off-by: TonyRowntree <33454202+TonyRowntree@users.noreply.github.com>

* Enhancing vault responses for corda os

Signed-off-by: Kumar, D. bd <d.bd.kumar@accenture.com>

* [fabric] Created the peer molecule scenario

Signed-off-by: TonyRowntree <33454202+TonyRowntree@users.noreply.github.com>

Co-authored-by: alvaropicazo <alvaro.picazo.haase@accenture.com>
Co-authored-by: Sownak Roy <20537268+sownak@users.noreply.github.com>
Co-authored-by: ragalz <r.galan.lopez@accenture.com>
Co-authored-by: Kumar, D. bd <d.bd.kumar@accenture.com>
Co-authored-by: Roy,Sownak <sownak.roy@accenture.com>
Co-authored-by: TonyRowntree <33454202+TonyRowntree@users.noreply.github.com>

diff --git a/platforms/hyperledger-fabric/charts/approve_chaincode/templates/approve_chaincode.yaml b/platforms/hyperledger-fabric/charts/approve_chaincode/templates/approve_chaincode.yaml
--- a/platforms/hyperledger-fabric/charts/approve_chaincode/templates/approve_chaincode.yaml
+++ b/platforms/hyperledger-fabric/charts/approve_chaincode/templates/approve_chaincode.yaml
@@ -1,11 +1,11 @@
 apiVersion: batch/v1
 kind: Job
 metadata:
-  name: approvechaincode-{{ $.Values.chaincode.name }}-{{ $.Values.chaincode.version }}
+  name: approvechaincode-{{ $.Values.peer.name }}-{{ $.Values.chaincode.name }}-{{ $.Values.chaincode.version }}
   namespace: {{ $.Values.metadata.namespace }}
   labels:
-    app: approvechaincode-{{ $.Values.chaincode.name }}-{{ $.Values.chaincode.version }}
-    app.kubernetes.io/name: approvechaincode-{{ $.Values.chaincode.name }}{{ $.Values.chaincode.version }}
+    app: approvechaincode-{{ $.Values.peer.name }}-{{ $.Values.chaincode.name }}-{{ $.Values.chaincode.version }}
+    app.kubernetes.io/name: approvechaincode-{{ $.Values.chaincode.name }}-{{ $.Values.chaincode.version }}
     helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
     app.kubernetes.io/managed-by: {{ .Release.Service }}
     app.kubernetes.io/instance: {{ .Release.Name }}
@@ -15,7 +15,7 @@ spec:
   template:
     metadata:
       labels:
-        app: approvechaincode-{{ $.Values.chaincode.name }}-{{ $.Values.chaincode.version }}
+        app: approvechaincode-{{ $.Values.peer.name }}-{{ $.Values.chaincode.name }}-{{ $.Values.chaincode.version }}
         app.kubernetes.io/name: approvechaincode-{{ $.Values.chaincode.name }}{{ $.Values.chaincode.version }}
         helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
         app.kubernetes.io/instance: {{ .Release.Name }}
@@ -58,11 +58,26 @@ spec:
         - |-
           #!/usr/bin/env sh
           validateVaultResponse () {
-          if echo ${2} | grep "errors"; then
-           echo "ERROR: unable to retrieve ${1}: ${2}"
-           exit 1
-           fi
+            if echo ${2} | grep "errors"; then
+              echo "ERROR: unable to retrieve ${1}: ${2}"
+              exit 1
+            fi
+            if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
+            then
+              http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
+              --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
+              ${VAULT_ADDR}/v1/${vault_secret_key})
+              curl_response=$?
+              if test "$http_code" != "200" ; then
+                  echo "Http response code from Vault - $http_code"
+                  if test "$curl_response" != "0"; then
+                     echo "Error: curl command failed with error code - $curl_response"
+                     exit 1
+                  fi
+              fi
+            fi
           }
+          
           KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
           echo "Getting secrets from Vault Server: ${VAULT_ADDR}"
           # Login to Vault and so I can get an approle token
@@ -80,7 +95,7 @@ spec:
             --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
             ${VAULT_ADDR}/v1/${vault_secret_key} | jq -r 'if .errors then . else . end')
 
-          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}"
+          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
 
           TLS_CA_CERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["ca.crt"]')
 
@@ -94,7 +109,7 @@ spec:
           LOOKUP_SECRET_RESPONSE=$(curl -sS  \
             --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
             ${VAULT_ADDR}/v1/${vault_secret_key} | jq -r 'if .errors then . else . end')
-          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}"
+          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
 
           ADMINCERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["admincerts"]')
           CACERTS=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["cacerts"]')
diff --git a/platforms/r3-corda/charts/nms/templates/deployment.yaml b/platforms/r3-corda/charts/nms/templates/deployment.yaml
--- a/platforms/r3-corda/charts/nms/templates/deployment.yaml
+++ b/platforms/r3-corda/charts/nms/templates/deployment.yaml
@@ -53,7 +53,10 @@ spec:
           - containerPort: {{ .Values.service.targetPort }}
         volumeMounts:
           - name: {{ .Values.nodeName }}-servicedata
-            mountPath: "{{ .Values.image.mountPath.basePath }}/db/"
+            mountPath: "{{ .Values.image.mountPath.basePath }}/db"
+            readOnly: false
+          - name: {{ .Values.nodeName }}-logs
+            mountPath: "{{ .Values.image.mountPath.basePath }}/logs"
             readOnly: false
           - name: certs
             mountPath: "{{ .Values.image.mountPath.basePath }}/db/certs"
@@ -61,6 +64,36 @@ spec:
           - name: creds
             mountPath: "/opt/creds"
             readOnly: false
+      - name: logs
+        image: "{{ .Values.image.initContainerName }}"
+        imagePullPolicy: {{ .Values.image.pullPolicy }}
+        command: ["sh", "-c"]
+        args:
+        - |-
+          cd /opt/networkmap/
+          COUNTER=1
+          NETWORK_ROOT_TRUST=/opt/networkmap/network-map-truststore.jks
+          while [ "$COUNTER" -le {{ $.Values.healthcheck.readinessthreshold }} ]
+          do
+            curl http://localhost:8080/network-map/truststore --output network-map-truststore.jks
+            if [ -f "$NETWORK_ROOT_TRUST" ]
+            then
+              echo "SUCCESS!"
+              echo "NMS running and fetched truststore"
+              break
+            else
+              COUNTER=`expr "$COUNTER" + 1`
+              sleep {{ $.Values.healthcheck.readinesscheckinterval }}
+            fi   
+          done 
+          if ["$COUNTER" -gt {{ $.Values.healthcheck.readinessthreshold }} ] 
+          then 
+            exit 1 
+          fi
+          while true; do tail -f ./logs/*.log 2>/dev/null; sleep 5; done
+        volumeMounts:
+        - name: {{ .Values.nodeName }}-logs
+          mountPath: "{{ .Values.image.mountPath.basePath }}/logs"
       initContainers:
       - name: init-certificates
         image: {{ .Values.image.initContainerName }}
@@ -82,12 +115,26 @@ spec:
         args:
         - |-
              #!/usr/bin/env sh
-             validateVaultResponse () {
-             if echo ${2} | grep "errors"; then
-              echo "ERROR: unable to retrieve ${1}: ${2}"
-              exit 1
-              fi
-             }
+              validateVaultResponse () {
+                if echo ${2} | grep "errors"; then
+                  echo "ERROR: unable to retrieve ${1}: ${2}"
+                  exit 1
+                fi
+                if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
+                then
+                  http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
+                  --header "X-Vault-Token: ${VAULT_TOKEN}" \
+                  ${VAULT_ADDR}/v1/${1})
+                  curl_response=$?
+                  if test "$http_code" != "200" ; then
+                      echo "Http response code from Vault - $http_code"
+                      if test "$curl_response" != "0"; then
+                        echo "Error: curl command failed with error code - $curl_response"
+                        exit 1
+                      fi
+                  fi
+                fi
+              }
 
              KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
              echo "Getting secrets from Vault Server"
@@ -98,7 +145,7 @@ spec:
 
              LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/{{ .Values.vault.certsecretprefix }} | jq -r 'if .errors then . else . end')
 
-             validateVaultResponse "secret (${{ .Values.vault.certsecretprefix }})" "${LOOKUP_SECRET_RESPONSE}"
+             validateVaultResponse "${{ .Values.vault.certsecretprefix }}" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
 
              ROOTCA_KEY=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["rootcakey"]')
              mkdir -p ${OUTPUT_PATH}/root;
@@ -135,12 +182,26 @@ spec:
         args:
         - |-
              #!/usr/bin/env sh
-             validateVaultResponse () {
-             if echo ${2} | grep "errors"; then
-              echo "ERROR: unable to retrieve ${1}: ${2}"
-              exit 1
-              fi
-             }
+              validateVaultResponse () {
+                if echo ${2} | grep "errors"; then
+                  echo "ERROR: unable to retrieve ${1}: ${2}"
+                  exit 1
+                fi
+                if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
+                then
+                  http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
+                  --header "X-Vault-Token: ${VAULT_TOKEN}" \
+                  ${VAULT_ADDR}/v1/${1})
+                  curl_response=$?
+                  if test "$http_code" != "200" ; then
+                      echo "Http response code from Vault - $http_code"
+                      if test "$curl_response" != "0"; then
+                        echo "Error: curl command failed with error code - $curl_response"
+                        exit 1
+                      fi
+                  fi
+                fi
+              }
 
              KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
              echo "Getting secrets from Vault Server"
@@ -151,6 +212,7 @@ spec:
              OUTPUT_PATH=${MOUNT_PATH}
              
              LOOKUP_PWD_RESPONSE_DB_PASS=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${DB_CRED_SECRET_PREFIX} | jq -r 'if .errors then . else . end')
+             validateVaultResponse "${DB_CRED_SECRET_PREFIX}" "${LOOKUP_PWD_RESPONSE_DB_PASS}" "LOOKUPSECRETRESPONSE"
              MONGODB_PASSWORD=$(echo ${LOOKUP_PWD_RESPONSE_DB_PASS} | jq -r '.data["mongodbPassword"]')
           
              echo "${MONGODB_PASSWORD}" >> ${MOUNT_PATH}/db_root_password
@@ -232,6 +294,9 @@ spec:
         - name: {{ .Values.nodeName }}-servicedata
           persistentVolumeClaim:
             claimName: {{ .Values.nodeName }}-pvc
+        - name: {{ .Values.nodeName }}-logs
+          persistentVolumeClaim:
+            claimName: {{ .Values.nodeName }}-pvc-logs
         - name: certs
           emptyDir:
             medium: Memory
