[corda-ent] Fix jobs, idman and docs (#1011)
Signed-off-by: sownak <sownak.roy@accenture.com>

diff --git a/platforms/corda-ent/charts/node-initial-registration/templates/job.yaml b/platforms/corda-ent/charts/node-initial-registration/templates/job.yaml
--- a/platforms/corda-ent/charts/node-initial-registration/templates/job.yaml
+++ b/platforms/corda-ent/charts/node-initial-registration/templates/job.yaml
@@ -205,10 +205,12 @@ spec:
           args:
           - |-
             #!/usr/bin/env sh
-
-            # setting up env to get secrets from vault
-            KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
-            VAULT_TOKEN=$(curl -sS --request POST ${VAULT_ADDR}/v1/auth/${KUBERNETES_AUTH_PATH}/login -H "Content-Type: application/json" -d '{"role":"'"${VAULT_APP_ROLE}"'","jwt":"'"${KUBE_SA_TOKEN}"'"}' | jq -r 'if .errors then . else .auth.client_token end')
+            validateVaultResponse () {
+              if echo ${2} | grep "errors"; then
+                 echo "ERROR: unable to retrieve ${1}: ${2}"
+                 exit 1
+              fi
+            }          
 
             # perform check if certificates are ready or not, and upload certificate into vault when ready
             COUNTER=1
@@ -218,6 +220,10 @@ spec:
                 if [ -e done.txt ]
                 then
                   echo "found certificates, performing vault put"
+                  # setting up env to get secrets from vault
+                  KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
+                  VAULT_TOKEN=$(curl -sS --request POST ${VAULT_ADDR}/v1/auth/${KUBERNETES_AUTH_PATH}/login -H "Content-Type: application/json" -d '{"role":"'"${VAULT_APP_ROLE}"'","jwt":"'"${KUBE_SA_TOKEN}"'"}' | jq -r 'if .errors then . else .auth.client_token end')
+                  validateVaultResponse 'vault login token' "${VAULT_TOKEN}"
                   (echo '{"nodekeystore.jks": "'; base64 ${BASE_DIR}/certificates/nodekeystore.jks; echo '"}') | curl -H "X-Vault-Token: ${VAULT_TOKEN}" -d @- ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/certs/nodekeystore
                   (echo '{"sslkeystore.jks": "'; base64 ${BASE_DIR}/certificates/sslkeystore.jks; echo '"}') | curl -H "X-Vault-Token: ${VAULT_TOKEN}" -d @- ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/certs/sslkeystore
                   (echo '{"truststore.jks": "'; base64 ${BASE_DIR}/certificates/truststore.jks; echo '"}') | curl -H "X-Vault-Token: ${VAULT_TOKEN}" -d @- ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/certs/truststore
@@ -228,6 +234,12 @@ spec:
                   COUNTER=`expr "$COUNTER" + 1`
                 fi
             done
+            if [ "$COUNTER" -gt {{ $.Values.vault.retries }} ]
+            then
+                echo "Retry attempted $COUNTER times, no files found. Giving up!"
+                exit 1
+                break
+            fi
           volumeMounts:
           - name: node-nodeinfo
             mountPath: /opt/corda/additional-node-infos
